apiVersion: v1
kind: Service
metadata:
 name: mygrafanaservice
 labels:
  app: monitoring
spec:
 selector:
  app: monitoring
 type: NodePort
 ports:
  - name: port2
    port: 3000
    targetPort: 3000