apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: "prompvc"
   labels: 
      name: "prom_pvc"

spec:
    accessModes:
      - ReadWriteOnce
    resources:
       requests:
         storage: 1Gi