apiVersion: v1
kind: Service
metadata:
 name: mypromservice
 labels:
  app: monitoring
spec:
 selector:
  app: monitoring
 type: NodePort
 ports:
  - name: port1
    port: 9090
    targetPort: 9090