apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: monitoring

  template:
    metadata:
      name: prometheus
      labels:
        app: monitoring


    spec:
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prompvc
        
      containers:
        - name: prometheus-container
          image: vimal13/prometheus
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/etc/prometheus/"
              name: prometheus-storage